### Numpy Task

In [1]:
import numpy as np
# 1~10까지의 요소를 ndarray에 담는다.
# ndarray1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
ndarray1 = np.arange(start=1, stop=11)
print(type(ndarray1), ndarray1)

<class 'numpy.ndarray'> [ 1  2  3  4  5  6  7  8  9 10]


In [2]:
# 3행 2열 list를 ndarray에 담고 각 요소는 순서대로 6, 5, 4, 3, 2, 1이다.
list2 = [[1, 2], [3, 4], [5, 6]]
ndarray2 = np.array(list2)
sorted_ndarray2 = np.sort(ndarray2, axis=0)[::-1, ::-1]
# ndarray1 = np.arange(start=6, stop=0, step=-1)
# ndarray2 = ndarray1.reshape((3, 2))
print(sorted_ndarray2)

[[6 5]
 [4 3]
 [2 1]]


In [3]:
# 4행 1열 ndarray, 순서대로 10, 8, 6, 4를 담는다.
# Transpose: 전치 행과 열을 바꿔준다.
ndarray1 = np.arange(start=10, stop=3, step=-2)
# ndarray1 = np.arange(start=4, stop=11, step=2)[::-1]
ndarray2 = ndarray1.reshape((4, 1))
print(ndarray2)

[[10]
 [ 8]
 [ 6]
 [ 4]]


In [4]:
# 1~10까지 요소를 ndarray에 담고 각 요소에 5씩 더해준다.
ndarray1 = np.arange(start=1, stop=11)
ndarray1 += 5

# list_ndarray1 = list(ndarray1)

# for i in range(len(list_ndarray1)):
#     list_ndarray1[i] += 5
    
# ndarray1 = np.array(list_ndarray1)
print(ndarray1)

[ 6  7  8  9 10 11 12 13 14 15]


In [5]:
# axis 0이 10인 shape이면서 모든 원소가 0, dtype은 int32인 ndarray만들기
# ndarray1 = np.arange(start=0, stop=10) * 0
ndarray1 = np.zeros((10,), dtype=np.int32)
print(ndarray1.dtype, ndarray1.shape)
print(ndarray1)

int32 (10,)
[0 0 0 0 0 0 0 0 0 0]


In [6]:
# axis 0이 3, axis 1이 4인 shape이면서 모든 원소가 1인 ndarray 만들기
# ndarray2 = np.zeros((3, 4)) + 1
ndarray2 = np.ones((3, 4))
print(ndarray2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
# axis 0이 5, 각 요소가 0~4인 ndarray 만들기
ndarray1 = np.arange(stop=5)
print(ndarray1)

[0 1 2 3 4]


In [8]:
# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=0, stop=16)

In [9]:
# 2 Dimension, axis 1은 2로 변경
ndarray2 = ndarray1.reshape((-1, 2))
print(ndarray2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [10]:
# 2 Dimension, axis 0은 8로 변경
ndarray2 = ndarray1.reshape((8, -1))
print(ndarray2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [11]:
# 3 Dimension으로 변경
ndarray3 = ndarray1.reshape((2, 2, -1))
print(ndarray3)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [12]:
# ndarray3을 axis 1이 1인 2차원 ndarray로 변환
ndarray2 = ndarray3.reshape((-1, 1))
print(ndarray2)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]


In [29]:
# ndarray3을 1 Dimension으로 변환
# ndarray1 = ndarray3.reshape((-1,))
# flatten(): 1차원으로 만들어주는 함수
ndarray1 = ndarray3.flatten()
print(ndarray1)

['한국' '영국' '러시아' '남아프리카 공화국' '미국']


In [14]:
# 1차원 ndarray 1~100까지 값 중 97값 추출하기
ndarray1 = np.arange(start=1, stop=101)
print(ndarray1)
print(ndarray1[-4])

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
97


In [15]:
# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=1, stop=21)

In [16]:
# 2차원 배열 axis 0은 4, axis 1은 5로 1~20 요소 값 중 15값 추출하기
ndarray2 = ndarray1.reshape((4, 5))
# print(ndarray2[ndarray2 == 15][0])
print(ndarray2[2, 4])

15


In [17]:
# 2 Dimension, axis 0은 5로 변경
ndarray2 = ndarray1.reshape((5, -1))
print(ndarray2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [18]:
# 2행의 4번째 숫자 출력
print(ndarray2[1, 3])

8


In [19]:
# 1~100중 짝수만 출력
ndarray1 = np.arange(start=1, stop=101)
even_ndarray1 = ndarray1[ndarray1 % 2 == 0]
print(even_ndarray1)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [20]:
# 위에서 구한 짝수들을 axis 0이 10인 2차원 배열로 변환 후 82~100까지 추출
ndarray2 = even_ndarray1.reshape(10, -1)
# print(ndarray2[[-2, -1]]) 2차원
print(ndarray2[ndarray2 >= 82]) # 추출은 1차원으로 가져오는게 좋다

[ 82  84  86  88  90  92  94  96  98 100]


In [21]:
# 위에서 구한 요소 중 (86, 100) 좌표 구하기
index = np.where(ndarray2 == 86)
print(index)
index = np.where(ndarray2 == 100)
print(index)
print("86의 좌표: (8, 2)")
print("100의 좌표: (9, 4)")

(array([8], dtype=int64), array([2], dtype=int64))
(array([9], dtype=int64), array([4], dtype=int64))
86의 좌표: (8, 2)
100의 좌표: (9, 4)


In [22]:
# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=1, stop=101)

In [23]:
# 각 요소중 1의 자리수가 2인 수들만 추출하기
print(ndarray1[ndarray1 % 10 == 2])

[ 2 12 22 32 42 52 62 72 82 92]


In [24]:
# 1~49요소 중 2와 5의 공배수 추출하기
result = ndarray1[(ndarray1 < 50) & (ndarray1 % 10 == 0)]
print(result)

[10 20 30 40]


In [25]:
# 위에서 추출한 공배수 중 20이상인 값만 추출하기
print(result[result >= 20])

[20 30 40]


In [26]:
# 데이터를 분석하여, 각 수치별 오름차순 및 내림차순 후 이름을 출력하세요.
# [[과일이름], [가격]], 가격별 내림차순
array1 = [['Mango', 'Apple', 'Pear', 'Pitch', 'Melon'], [1500, 1800, 2000, 2500, 8500]]
ndarray2 = np.array(array1[0])
price_ndarray2 = np.array(array1[1])

price_sorted_index = np.argsort(price_ndarray2)[::-1]

print(price_sorted_index)
print(ndarray2[price_sorted_index])

[4 3 2 1 0]
['Melon' 'Pitch' 'Pear' 'Apple' 'Mango']


In [27]:
# [[이름], [나이], [학점]], 나이별 내림차순, 학점별 오름차순
array2 = [['둘리', '또치', '길동', '도너', '마이콜'], [7, 9, 40, 5, 20], ['C', 'A', 'B', 'F', 'D']]
ndarray2 = np.array(array2[0])
age_ndarray2 = np.array(array2[1])
score_ndarray2 = np.array(array2[2])

age_sorted_index = np.argsort(age_ndarray2)[::-1]
print(age_sorted_index)

score_sorted_index = np.argsort(score_ndarray2)
print(score_sorted_index)

print(ndarray2[age_sorted_index])
print(ndarray2[score_sorted_index])

[2 4 1 0 3]
[1 2 0 4 3]
['길동' '마이콜' '또치' '둘리' '도너']
['또치' '길동' '둘리' '마이콜' '도너']


In [28]:
# [[국가이름], [GDP 성장률]], GDP 성장률별 오름차순
array3 = [['한국', '영국', '러시아', '남아프리카 공화국', '미국'], ['1.7%', '-0.6%', '0.3%', '1.2%', '1.4%']]
ndarray3 = np.array(array3[0])
gdp_ndarray3 = np.array(array3[1])
gdp_sorted_index = np.argsort(gdp_ndarray3)
print(ndarray3[gdp_sorted_index])

['영국' '러시아' '남아프리카 공화국' '미국' '한국']


In [ ]:
# 강사님 코드
import numpy as np

# 1~10까지의 요소를 ndarray에 담는다.
# ndarray1 = np.array(list(range(1, 11)))
ndarray1 = np.arange(start=1, stop=11)
print(ndarray1)

# 3행 2열 list를 ndarray에 담고 각 요소는 순서대로 6, 5, 4, 3, 2, 1이다.
python_list = []
python_list.append([6 - i for i in range(2)])
python_list.append([4 - i for i in range(2)])
python_list.append([2 - i for i in range(2)])

ndarray2 = np.array(python_list)
print(type(ndarray2), ndarray2.shape, ndarray2.ndim, ndarray2.dtype, sep="\n")

# 4행 1열 ndarray, 순서대로 10, 8, 6, 4를 담는다
# Transpose: 전치, 행과 열을 바꿔준다.
ndarray2 = np.array([[(5 - i) * 2 for i in range(4)]]).T
print(ndarray2)

# 1~10까지 요소를 ndarray에 담고 각 요소에 5씩 더해준다.
ndarray1 = np.arange(start=1, stop=11)
ndarray1_oper = ndarray1 + 5
print(ndarray1_oper)

# axis 0이 10인 shape이면서 모든 원소가 0, dtype은 int32인 ndarray만들기
ndarray1 = np.zeros((10,), dtype=np.int32)
print(ndarray1, ndarray1.shape, sep="\n")

# axis 0이 3, axis1이 4인 shape이면서 모든 원소가 1인 ndarray 만들기
ndarray1 = np.ones((3, 4), dtype=np.int8)
print(ndarray1, ndarray1.shape, sep="\n")

# axis 0이 5, 각 요소가 0~4인 ndarray 만들기
ndarray1 = np.arange(stop=5)
print(ndarray1, ndarray1.shape, sep="\n")

# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=0, stop=16)

# 2 Dimension, axis 1은 2로 변경
ndarray2 = ndarray1.reshape((-1, 2))
print(ndarray2, ndarray2.shape, sep="\n")

# 2 Dimension, axis 0은 8로 변경
ndarray2 = ndarray1.reshape((8, -1))
print(ndarray2, ndarray2.shape, sep="\n")

# 3 Dimension으로 변경
ndarray3 = ndarray1.reshape((4, 2, -1))
print(ndarray3, ndarray3.shape, sep="\n")

# ndarray3을 axis 1이 1인 2차원 ndarray로 변환
ndarray2 = ndarray3.reshape((-1, 1))
print(ndarray2, ndarray2.shape, sep="\n")

# ndarray3을 1 Dimension으로 변환
# ndarray1 = ndarray3.reshape((-1, ))
ndarray1 = ndarray3.flatten()
print(ndarray1, ndarray1.shape, sep="\n")

# 1차원 ndarray 1~100까지 값 중 97값 추출하기
ndarray1 = np.arange(start=1, stop=101)
print(ndarray1[96])

# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=1, stop=21)

# 2차원 배열 axis 0은 4, axis 1은 5로 1~20 요소 값 중 15값 추출하기
ndarray2 = ndarray1.reshape((4, 5))
print(ndarray2[2, 4])

# 2 Dimension, axis 0은 5로 변경
ndarray2 = ndarray1.reshape((5, -1))

# 2행의 4번째 숫자 출력
print(ndarray2[1, 3])

# 1~100중 짝수만 출력
ndarray1 = np.arange(start=1, stop=101)
ndarray1_even = ndarray1[ndarray1 % 2 == 0]

# 위에서 구한 짝수들을 axis 0이 10인 2차원 배열로 변환 후 82~100까지 추출
ndarray2_even = ndarray1_even.reshape((10, -1))
ndarray2_even_ex = ndarray2_even[8:]

# 위에서 구한 요소 중 (86, 100) 좌표 구하기
print(ndarray2_even_ex)
print("86의 좌표(x, y): (0, 2)")
print("100의 좌표(x, y): (1, 4)")
print(ndarray2_even_ex[0, 2], ndarray2_even_ex[1, 4])

# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
ndarray1 = np.arange(start=1, stop=101)

# 각 요소중 1의 자리수가 2인 수들만 추출하기
print(ndarray1[ndarray1 % 10 == 2])

# 1~49요소 중 2와 5의 공배수 추출하기
ndarray1 = np.arange(start=1, stop=50)
condition1 = ndarray1 % 2 == 0
condition2 = ndarray1 % 5 == 0
condition3 = condition1 & condition2
result = ndarray1[condition3]

# 위에서 추출한 공배수 중 20이상인 값만 추출하기
condition = result >= 20
print(result[condition])

# 데이터를 분석하여, 각 수치별 오름차순 및 내림차순 후 이름을 출력하세요.
# [[과일이름], [가격]], 가격별 내림차순
array1 = [['Mango', 'Apple', 'Pear', 'Pitch', 'Melon'], [1500, 1800, 2000, 2500, 8500]]

ndarray2 = np.array(array1)
fruit_name = ndarray2[:1].flatten()
fruit_price = ndarray2[-1]

print(fruit_name, fruit_price, sep="\n")

fruit_name_asc = fruit_name[fruit_price.argsort()[::-1]]
print(fruit_name_asc)

# [[이름], [나이], [학점]], 나이별 내림차순, 학점별 오름차순
array2 = [['둘리', '또치', '길동', '도너', '마이콜'], [7, 9, 40, 5, 20], ['C', 'A', 'B', 'F', 'D']]

ndarray2 = np.array(array2)
names = ndarray2[:1].flatten()
ages = ndarray2[1].astype(np.int16)
grades = ndarray2[-1]

print(names, ages, grades)

print(names[ages.argsort()[::-1]])
print(names[grades.argsort()])

# [[국가이름], [GDP 성장률]], GDP 성장률별 오름차순
array3 = [['한국', '영국', '러시아', '남아프리카 공화국', '미국'], ['1.7%', '-0.6%', '0.3%', '1.2%', '1.4%']]
gdp_list = []
ndarray2 = np.array(array3)

nations = ndarray2[0]
gdps = ndarray2[1]


for gdp in gdps:
    gdp_list.append(gdp.replace('%', ''))

gdps = np.array(gdp_list, dtype=np.float16)

print(nations[gdps.argsort()])